### ISSUE TITLE
Current version does not work

### ISSUE THREAD

**Issue by kenmaglio** [AttilioCapocchiani/vscode-azure-boards#17]
I have read through the readme. 

I have created a Personal Access Token, with the two read permissions needed. 

My DevOps Explorer Query window is empty. 

Nothing appears to work even if I go through the F1  DevOps Open Menu.

**Comment by AttilioCapocchiani** [comment]
Hi, did you create a query on Azure DevOps? If you follow the guided setup, you have to create a query on Azure DevOps and then manually add pasting its id (you can get that from the URL)

**Comment by kenmaglio** [comment]
Hey there, I'm not sure what the guided setup is?
I went through some of the initial buttons when I installed, but then exited out maybe too quick.

Is there a way to get that to open again?  Or do I have to remove/re-add ?

**Comment by AttilioCapocchiani** [comment]
When you opened the extension for the first time, a welcome screen was shown. No problem, you can still add queries in a second moment, just following these steps:

- Configure a Query on Azure DevOps (due to DevOps API limitations I can't access all the work items, so you have to manually create a query). Once you have done so you should have something that looks like this. In your url you will have `dev.azure.com/<organization>/<project>/_queries/query/<query_id>`. The last one is the id you will have to copy
![step 1](https://user-images.githubusercontent.com/14235479/123074858-faae5f00-d417-11eb-8c45-9af77fa24642.png)
- Now go on VSCode, open the commands section and choose _Add Query_
<img width="613" alt="Schermata 2021-06-23 alle 11 42 17" src="https://user-images.githubusercontent.com/14235479/123074979-1285e300-d418-11eb-8752-2d5fdbaabe69.png">

- If this is the first time, you have to insert your organization name (again, DevOps API doesn't let me access to your organizations), but it will be saved so you don't have to type it in the future
- Then all your projects will be listed, **select the project that contains your query** (weird, I can't access organizations, but I can access projects)
- Then you have to put the Id of your query (the one you get from the URL, in my screenshot, the partially blurred info)
- As last, you can give that query a more understandable name
- You should be able to see all your work items :)

**Comment by AttilioCapocchiani** [comment]
Hi @kenmaglio, did you manage to solve your problem? Can I close this issue?

Attilio

**Comment by kenmaglio** [comment]
@AttilioCapocchiani  You can close it out good sir. Thanks for the help.
